# Latar Belakang {#pendahuluan}

World Health Organization (WHO) merekomendasikan bahwa setiap negara dalam menyelenggarakan pelayanan kesehatan perlu mengutamakan prinsip continuum of care dimana fasilitas layanan kesehatan (fasyankes) dapat memantau kesehatan pasien secara berkesinambungan . Pemantauan kondisi kesehatan pasien secara berkesinambungan dan komprehensif dapat membantu para tenaga kesehatan dalam mengevaluasi tata laksana kesehatan yang telah diberikan. Hasil evaluasi tata laksana yang baik dapat memudahkan komunikasi antar Fasyankes untuk melakukan rujukan yang efektif dan efisien apabila diperlukan. Pencatatan data yang tidak lengkap, inkonsisten, dan tidak akurat merupakan faktor utama penurunan kualitas dalam pelayanan kesehatan. Pencatatan data yang lengkap dan terstandardisasi dapat memudahkan penyusunan kebijakan berbasis bukti, perencanaan fasyankes dalam meningkatkan kompetensi, serta mengurangi beban kerja administratif puskesmas dan rumah sakit yang hingga kini menggunakan lebih dari 60 aplikasi sekaligus untuk memenuhi administrasi pelaporan nasional.

## Fragmentasi Data dan Sistem Informasi Kesehatan

Inovasi digital kesehatan yang terus bertumbuh di tengah-tengah masyarakat serta ketiadaan standar pertukaran data dan terminologi kesehatan di Indonesia menyebabkan penyedia layanan kesehatan (provider) mendapatkan informasi parsial. Banyak yang belum terpetakan dari data yang ada. Platform data terintegrasi sangat dibutuhkan untuk dapat mendukung internal Fasyankes dalam memaksimalkan pelayanan rumah sakit, terutama untuk memprediksi penyakit dan luaran dari hasil perawatan pasien.

Pengalaman Indonesia dalam menangani pandemi COVID-19 di Indonesia juga menunjukkan pentingnya interoperabilitas antar sistem informasi kesehatan. Penanganan pandemi yang masih sporadis dengan pendekatan pembuatan kebijakan yang masih tradisional mengekspos sistem ketahanan kesehatan Indonesia yang sangat rentan, dalam kondisi darurat kualitas mitigasi sangat tergantung pada efektivitas alokasi sumber daya pada sektor kritikal dan respon yang terkoordinasi pada lintas sektor dengan waktu sesingkat mungkin . Ketahanan kesehatan berperan sangat penting bagi suatu negara. Ketahanan kesehatan masyarakat global atau global public health security didefinisikan sebagai kegiatan yang diperlukan, baik praktis maupun reaktif, untuk meminimalkan bahaya dan dampak peristiwa kesehatan masyarakat yang membahayakan kesehatan masyarakat lintas wilayah geografis dan batas internasional . Membangun sistem ketahanan kesehatan yang responsif dan efektif membutuhkan pengambilan keputusan berdasarkan data yang robust dan real time.

## Kebutuhan Standarisasi Pertukaran Data dan Informasi Kesehatan

Peraturan Menteri Kesehatan Republik Indonesia No 21 Tahun 2020 tentang Rencana Strategis Kementerian Kesehatan Tahun 2020 – 2024 telah mensyaratkan adanya upaya perubahan tata kelola pembangunan kesehatan yang meliputi integrasi sistem informasi, penelitian, dan pengembangan kesehatan. Proses digitalisasi kesehatan di tingkat nasional hingga daerah tentu tidaklah mudah dan memerlukan perencanaan. Oleh karena itu, proses digitalisasi kesehatan baik di tingkat nasional hingga daerah perlu dimulai direncanakan dengan seksama. Hal tersebut dirancang dalam peta jalan transformasi teknologi kesehatan.
Saat ini, Health Level Seven International - Fast Healthcare Interoperability Resources (HL7-FHIR) adalah standar terkini dalam pertukaran dan interoperabilitas data kesehatan. HL7-FHIR menggunakan fitur Application Programming Interface (API) yang sudah banyak dikenal oleh pengembang sistem informasi untuk bertukar data lintas platform dan teknologi yang berbeda. Pertukaran Informasi Kesehatan, Sistem Informasi Rumah Sakit, dan bahkan perusahaan teknologi besar, seperti Google dan Apple, menggunakan HL7-FHIR dalam menangani data kesehatan. Google Healthcare menyediakan API yang dapat diakses oleh rekam medis elektronik (RME) untuk berbagi data dengan aplikasi lainnya (begitu juga sebaliknya). Apple menggunakan HL7-FHIR untuk menghubungkan Apple Health App ke berbagai RME/RKE dan bahkan perangkat yang dapat dikenakan seperti Apple Watch.

Oleh karena kemudahan penggunaannya, FHIR telah mendorong pengembangan lebih banyak aplikasi yang berhubungan dengan kesehatan, di luar RME tradisional atau Rekam Medis Kesehatan (RKE). Termasuk pengembangan aplikasi mobile atau aplikasi berbasis wearable devices. HL7-FHIR memanfaatkan penggunaan API untuk meningkatkan akses ke data kesehatan yang digunakan oleh RME yang berbeda. Negara-negara di seluruh dunia, seperti Amerika Serikat, Belanda, dan di Asia (Vietnam dan Filipina) mengadopsi HL7-FHIR sebagai standar dasar pertukaran informasi kesehatan di masing-masing negara mereka.

Selain menggunakan standar format interoperabilitas HL7 FHIR, terminologi kesehatan yang digunakan sebagai alat komunikasi intra maupun antar fasilitas kesehatan juga perlu dilakukan standardisasi. Standarisasi terminologi kesehatan menjadi penting untuk menyeragamkan istilah-istilah medis, tingkatan fasyankes, nama unit di dalam fasyankes, hingga dokumen-dokumen formal yang berhubungan dengan kesehatan.

Halaman ini akan mengantarkan Anda memahami standar pertukaran data kesehatan yang berlaku di Indonesia dan mengimplementasikan standar tersebut di fasyankes atau organisasi Anda.
