# Standar Interoperabilitas Kesehatan

Bab ini akan menjelaskan berbagai macam standar yang telah diimplementasikan di Indonesia, terutama oleh Kemenkes. Beberapa standar yang telah digunakan antara lain :

1.	HL7 FHIR
2.	SNOMED-CT
3.	LOINC

## HL7 FHIR
Standar HL7 FHIR (singkatan dari Fast Healthcare Interoperable Resources, diucapkan seperti “fire”) merupakan salah satu standar interoperabilitas sistem informasi kesehatan yang dikembangkan oleh organisasi oleh HL7. Standar ini mendukung pertukaran data antar aplikasi dalam konteks pelayanan kesehatan. HL7 FHIR merupakan pengembangan versi keempat menggabungkan keunggulan-keunggulan dari standar yang telah dikembangkan sebelumnya (HL7 v2, v3, dan CDA) dan berfokus kepada kemudahan implementasi yang ketat.

Singkatnya, FHIR memiliki keunggulan dalam :

* Lebih mudah dan lebih murah daripada standar lain yang sebanding:
  + Lebih cepat untuk dipelajari, diterapkan, dan dipecahkan (Anda seharusnya dapat "mencari tahu" lebih dari akhir pekan dan standar dikirimkan dengan toolkit dan contoh).
  + Memiliki komunitas yang dinamis dan open source dan sering mengadakan connectathon.
  + Menggunakan teknologi modern, sama seperti yang digunakan oleh mis. Facebook, Twitter, dan Google.
  + Ada lebih banyak orang yang akrab dengan teknologi ini (dengan demikian konsultan lebih murah).
* Project FHIR yang sedang diimplementasikan sekarang:
  + AS : ONC, SMART, Intermountain, CommonWell
  + Inggris : NHS 
  + Selandia Baru : Orion Health
  + Norwegia : Helse Vest
  + Integrating Healthcare Enterprise (IHE) Profiles
  + 70 implementasi, 20 negara (per 2014)
* Kemungkinan berdampak signifikan terhadap IT Kesehatan:
  + baik skala yang sederhana hingga yang kompleks
  + fleksibel, gratis, dan bersumber terbuka

## Mengapa Menggunakan HL7 FHIR?
FHIR menawarkan banyak peningkatan dari standar yang telah dikembangkan sebelumnya oleh HL7 :

* Fokus kepada implementasi : cepat dan mudah diterapkan (beberapa pengembang dapat membuat antarmuka sederhana dalam satu hari)
* Beberapa perpustakaan implementasi, banyak contoh tersedia untuk memulai pengembangan
* Spesifikasi gratis untuk digunakan tanpa batasan
* Interoperabilitas out-of-the-box: sumber daya dasar dapat digunakan apa adanya, tetapi juga dapat disesuaikan sesuai kebutuhan - yang sering terjadi - untuk kebutuhan lokal menggunakan Profil, Ekstensi, Terminologi, dan lainnya
* Jalur pengembangan evolusioner dari HL7 Versi 2 dan CDA: standar dapat hidup berdampingan dan saling memanfaatkan
* Fondasi yang kuat dalam standar Web: XML, JSON, HTTP, OAuth, dll.
* Dukungan untuk arsitektur RESTful, pertukaran informasi yang lancar menggunakan pesan atau dokumen, dan arsitektur berbasis layanan
* Spesifikasi ringkas dan mudah dipahami
* Format serialisasi yang dapat dibaca manusia untuk kemudahan penggunaan oleh pengembang
* Analisis berbasis ontologi dengan pemetaan formal untuk kebenaran (dalam pengembangan)

## Contoh Aplikasi Penggunaan HL7 FHIR
FHIR dapat digunakan untuk berbagai aplikasi seperti :

* Pertukaran data antar sistem dalam satu institusi (antara EMR, PACS, LIS, dll)
* Di tingkat regional, misal dalam Sistem Informasi Kesehatan Daerah di tingkat provinsi maupun beberapa provinsi yang berdekatan.
* Di tingkat nasional, misal di Sistem Informasi Kesehatan Nasional
* FHIR juga diaplikasikan di model Internet of Things menghubungkan wearable devices dengan rekam medis elektronik yang dapat diakes melalui smartphone seperti pada Apple Health.

## Filosofi Dibalik HL7 FHIR
FHIR tidak menyelesaikan tantangan interoperabilitas yang sangat sulit – seperti alur kerja dan kebijakan perbedaan antara organisasi, dan variabilitas dalam data yang ditangkap dan ditemukan di lokasi yang berbeda konteks penggunaan. FHIR bertujuan untuk membuat pelaksanaan pertukaran data sesederhana mungkin, untuk membuka jalan bagi pemecahan masalah interoperabilitas yang sulit ini.

Filosofi desain FHIR dapat diringkas sebagai berikut:

* Fokus pada Implementer – mudah dipahami oleh pengembang, banyak tools yang tersedia, API, dan contoh use case yang bekerja.
* Menargetkan dukungan untuk skenario umum dengan menyediakan resources yang banyak digunakan – namun pengguna dapat menambahkan resources yang belum ada dengan konsep ekstensi.
* Memanfaatkan teknologi web lintas industri - gunakan teknologi lintas industri yang sama seperti Google, Facebook dan lainnya (mis. XML, JSON, HTTPS, OAuth).
* Memerlukan keterbacaan manusia sebagai tingkat dasar interoperabilitas – sebagai opsi mundur untuk aplikasi tidak dapat menginterpretasikan konten terstruktur – sebuah pelajaran dari CDA.
* Membuat konten tersedia secara bebas – FHIR memiliki lisensi 'sumber terbuka'.
* Mendukung berbagai paradigma & arsitektur – FHIR memanfaatkan model dan profil data yang sama (lihat detail di bawah) di mana pun terlepas dari pendekatan interoperabilitas (REST, Documents, Pesan, Layanan). Ini adalah pelajaran dari HL7 versi 3, dengan model yang berbeda digunakan tergantung pada pendekatan integrasi, yang mengarah ke implementasi tambahan tantangan.

